BBPATH .= ":${LAYERDIR}"

BBFILE_COLLECTIONS += "meta-custom-bsp"

BBFILES += "\
  ${LAYERDIR}/recipes-*/*/*.bb \
  ${LAYERDIR}/recipes-*/*/*.bbappend \
"

BBFILE_PATTERN_meta-custom-bsp := "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-custom-bsp = "120"
LAYERSERIES_COMPAT_meta-custom-bsp = "scarthgap"
