DISTRO = "os"

require conf/distro/defaultsetup.conf

DISTROOVERRIDES:append = ":os"

DISTRO_FEATURES:append = " systemd pam seccomp usrmerge virtualization"

DISTRO_FEATURES:append = " os-secureboot-handoff"
DISTROOVERRIDES:append = ":os-secureboot-handoff"

VIRTUAL-RUNTIME_init_manager = "systemd"
VIRTUAL-RUNTIME_initscripts = ""

IMAGE_INSTALL:append = " \
    podman \
    conmon \
    crun \
    slirp4netns \
    fuse-overlayfs \
    cni \
"

IMAGE_INSTALL:append = " \
    python3-core \
    python3-modules \
    curl \
"
IMAGE_INSTALL:append = " \
    file \
    curl \
    busybox \
"
