#@TYPE: Machine
#@NAME: custom-orin-nano
#@DESCRIPTION: Based on p3768-0000-p3767-0004 (Orin Nano 4GB)

# Inherit the based machine from meta-tegra
require conf/machine/p3768-0000-p3767-0004.conf
require conf/machine/include/custom-jon-bb0.inc

MACHINEOVERRIDES .= ":p3768-0000-p3767-0004"

# Make our custom BCT/pinmux selected when tegra-flashvars generates flashvars
TEGRA_FLASHVAR_PINMUX_CONFIG = "tegra234-custom-jon4-bb0-pinmux.dtsi"
TEGRA_FLASHVAR_PMC_CONFIG    = "tegra234-custom-jon4-bb0-padvoltage-default.dtsi"
