#@TYPE: Machine
#@NAME: custom-orin-nano
#@DESCRIPTION: Based on p3768-0000-p3767-0003 (Orin Nano 8GB)

# Inherit the based machine from meta-tegra
require conf/machine/p3768-0000-p3767-0003.conf
require conf/machine/include/custom-jon-bb0.inc

# Add our machine override so bbappends can target it
MACHINEOVERRIDES .= ":p3768-0000-p3767-0003"

USE_REDUNDANT_FLASH_LAYOUT_DEFAULT = "1"
HAS_REDUNDANT_PARTITION_LAYOUT_EXTERNAL = "1"

ROOTFSPART_SIZE_REDUNDANT = "10737418240"

