#@TYPE: Machine
#@NAME: custom-orin-nano
#@DESCRIPTION: Based on p3768-0000-p3767-0004 (Orin Nano 4GB)

# Inherit the based machine from meta-tegra
require conf/machine/p3768-0000-p3767-0004.conf

# Add our machine override so bbappends can target it
MACHINEOVERRIDES:prepend = "custom-jon4-bb0-4:"

USE_REDUNDANT_FLASH_LAYOUT_DEFAULT = "1"
HAS_REDUNDANT_PARTITION_LAYOUT_EXTERNAL = "1"

ROOTFSPART_SIZE_REDUNDANT = "10737418240"

# Make our custom BCT/pinmux selected when tegra-flashvars generates flashvars
TEGRA_FLASHVAR_PINMUX_CONFIG = "tegra234-custom-jon4-bb0-pinmux.dtsi"
TEGRA_FLASHVAR_PMC_CONFIG    = "tegra234-custom-jon4-bb0-padvoltage-default.dtsi"

