BBPATH .= ":${LAYERDIR}"

BBFILE_COLLECTIONS += "custom-bsp-2"

BBFILES += "\
  ${LAYERDIR}/recipes-*/*/*.bb \
  ${LAYERDIR}/recipes-*/*/*.bbappend \
  ${LAYERDIR}/recipes-*/*/*/*.bbappend \
  ${LAYERDIR}/recipes-*/*/*/*/*.bbappend \
"

BBFILE_PATTERN_custom-bsp-2 := "^${LAYERDIR}/"
BBFILE_PRIORITY_custom-bsp-2 = "120"
LAYERSERIES_COMPAT_custom-bsp-2 = "scarthgap"
