inherit os-secureboot-public

# Run only when the feature is enabled
IMAGE_POSTPROCESS_COMMAND:append:os-secureboot-handoff = " os_secureboot_export_public; "
IMAGE_POSTPROCESS_COMMAND:append:os-secureboot-handoff = " os_secureboot_assert_no_private_in_handoff; "
IMAGE_POSTPROCESS_COMMAND:append = " os_secureboot_handoff; "

do_image[depends] += "os-secureboot-fusexml:do_deploy"
do_image[depends] += "lft-minimal:do_deploy"

do_image_complete[depends] += "os-secureboot-uefi-assets:do_deploy"
do_image_complete[depends] += "os-secureboot-uefi-stage2:do_deploy"

python os_secureboot_handoff () {
    import os, glob, shutil

    deploy = d.getVar("DEPLOY_DIR_IMAGE")
    outdir = os.path.join(deploy, "secureboot-handoff")
    os.makedirs(outdir, exist_ok=True)

    # copy newest tegraflash tarball
    tf = sorted(glob.glob(os.path.join(deploy, "*.tegraflash.tar.gz")))
    if tf:
        shutil.copy2(tf[-1], outdir)

    # copy newest ESP
    esp = sorted(glob.glob(os.path.join(deploy, "tegra-espimage-*.esp")))
    if esp:
        shutil.copy2(esp[-1], outdir)

    # copy kernel Image + initrd + dtbs if present
    for pat in ["Image", "initrd*", "*.dtb", "*.dtbo", "extlinux.conf"]:
        for f in glob.glob(os.path.join(deploy, pat)):
            shutil.copy2(f, outdir)

    # add a small readme for the flashing host
    readme = os.path.join(outdir, "README.txt")
    with open(readme, "w") as fp:
        fp.write("This folder is generated by Yocto for Jetson secure boot handoff.\n")
        fp.write("Use minimal Linux_for_Tegra (bootloader + tools/kernel_flash) on flash host.\n")
        fp.write("Next steps: sign + flash using l4t_initrd_flash.sh and tegrasign.\n")
    
    # Copy vendored minimal Linux_for_Tegra flash tools into handoff
    lft_src = os.path.join(deploy, "lft-minimal", "Linux_for_Tegra")
    if os.path.isdir(lft_src):
        dst = os.path.join(outdir, "flash-tools", "Linux_for_Tegra")
        if os.path.exists(dst):
            shutil.rmtree(dst)
        os.makedirs(os.path.dirname(dst), exist_ok=True)
        shutil.copytree(lft_src, dst, symlinks=True)
    
    # Placeholders for hardware-secureboot workflow
    for p in ["PKC", "SBK"]:
        os.makedirs(os.path.join(outdir, p), exist_ok=True)

    # Copy only PUBLIC PKC files into handoff
    pkc_src = os.path.join(deploy, "secureboot", "pkc")
    pkc_dst = os.path.join(outdir, "PKC")
    if os.path.isdir(pkc_src):
        os.makedirs(pkc_dst, exist_ok=True)
        for name in ["pkc_rsa3072_pub.pem", "pkc_rsa3072_pub.pem.sha256", "README.txt"]:
            src = os.path.join(pkc_src, name)
            if os.path.exists(src):
                shutil.copy2(src, pkc_dst)

    # Placeholder fuse config file (you will fill it later on flash host)
    fuse_placeholder = os.path.join(outdir, "fuse.xml")
    if not os.path.exists(fuse_placeholder):
        with open(fuse_placeholder, "w") as fp:
            fp.write("<!-- Placeholder fuse.xml. Fill with correct values before burning fuses. -->\n")
    
    # Copy generated fuse.xml into handoff
    fuse_src_dir = os.path.join(deploy, "secureboot", "fusexml")
    if os.path.isdir(fuse_src_dir):
        for name in ["fuse.xml", "pkc_rsa3072.hash", "pkc_rsa3072.pubkey", "README.txt"]:
            src = os.path.join(fuse_src_dir, name)
            if os.path.exists(src):
                shutil.copy2(src, outdir)    

}
IMAGE_POSTPROCESS_COMMAND:append = " os_secureboot_handoff; "

