BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb "
BBFILE_COLLECTIONS += "meta-custom-bsp"
BBFILE_PATTERN_meta-custom-bsp = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-custom-bsp = "5"

LAYERDEPENDS_meta-custom-bsp = "core"
