BBPATH .= ":${LAYERDIR}"

BBFILE_COLLECTIONS += "os-os"

BBFILES += "\
  ${LAYERDIR}/recipes-*/*/*.bb \
  ${LAYERDIR}/recipes-*/*/*.bbappend \
  ${LAYERDIR}/recipes-*/*/*/*.bbappend \
  ${LAYERDIR}/recipes-*/*/*/*/*.bbappend \
"

BBFILE_PATTERN_os-os := "^${LAYERDIR}/"
BBFILE_PRIORITY_os-os = "120"
LAYERSERIES_COMPAT_os-os = "scarthgap"
